services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - tachi-volume:/data/db
  redis:
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - tachi-redis:/data
  tachi-dev:
    user: "${UID}:${GID}"
    tty: true
    container_name: tachi-dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080" # server
      - "3000:3000" # client
      - "3001:3001" # docs
    volumes:
      - ./:/tachi
      # don't let pnpm's node_modules linkery bleed out of its container
      - /tachi/node_modules/
      - /tachi/.pnpm-store
volumes:
  tachi-volume:
  tachi-redis:
  tachi-logs:
