services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - tachi-volume:/data/db
  redis:
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - tachi-redis:/data
  tachi-server:
    container_name: tachi-server
    build:
      dockerfile: Dockerfile.server
      target: dev
    depends_on:
      bootstrap:
        condition: service_completed_successfully
      redis:
        condition: service_started
      mongo:
        condition: service_started
    links:
      - redis
      - mongo
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis
      MONGO_URL: mongo
      PORT: 8080
      NODE_ENV: "dev"
  tachi-client:
    container_name: tachi-client

    depends_on:
      bootstrap:
        condition: service_completed_successfully

    build:
      dockerfile: Dockerfile.client
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  tachi-seeds:
    container_name: tachi-seeds
    build:
      dockerfile: Dockerfile.seeds
    volumes:
      - ./:/app
  bootstrap:
    container_name: tachi-bootstrap
    build:
      dockerfile: Dockerfile.bootstrap
    volumes:
      - ./:/app
    links:
      - redis
      - mongo
    environment:
      REDIS_URL: redis
      MONGO_URL: mongo
      PORT: 8080
      NODE_ENV: "dev"
  tachi-docs:
    container_name: tachi-docs
    build:
      dockerfile: Dockerfile.docs
    ports:
      - "3001:8000"
    volumes:
      - ./:/app
volumes:
  tachi-volume:
  tachi-redis:
  tachi-logs:
