apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://tachi-prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres (tachi_dev)
    type: postgres
    access: proxy
    url: tachi-postgres:5432
    user: grafana_ro
    secureJsonData:
      password: grafana_ro
    jsonData:
      database: tachi_dev
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: true

  - name: Postgres (kamai)
    type: postgres
    access: proxy
    url: tachi-postgres:5432
    user: tachi
    secureJsonData:
      password: tachi
    jsonData:
      database: kamai
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: true

  - name: Postgres (boku)
    type: postgres
    access: proxy
    url: tachi-postgres:5432
    user: tachi
    secureJsonData:
      password: tachi
    jsonData:
      database: boku
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: true
