name: Common CI/CD

on:
  push:
    branches:
      - "main"
    paths:
      - "common/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "common/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm --filter tachi-common... --filter . install

      - name: Run Tests
        run: pnpm --filter tachi-common test
        env:
          NODE_ENV: "test"
