name: Common CI/CD

on:
  push:
    branches:
      - "main"
    paths:
      - "typescript/common/**"
      - ".github/workflows/common.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "typescript/common/**"
      - ".github/workflows/common.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zkldi/tachi-ci:main
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Linter
        run: bun run --filter tachi-common lint
        env:
          NODE_ENV: "test"

      - name: Run Tests
        run: bun run --filter tachi-common test
        env:
          NODE_ENV: "test"
